#!/bin/sh

### BEGIN INIT INFO
# Provides:	     nginx
# Required-Start:    $local_fs
# Required-Stop:     $local_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: starts the nginx web server
# Description:       starts nginx using start-stop-daemon
### END INIT INFO

DESC=nginx
NAME=nginx
DAEMON=/usr/local/nginx/sbin/nginx
PID_PATH=/var/run/nginx.pid

# Function that starts the daemon/service
#
do_start()
{
    echo -n "start $DESC:\n"
    start-stop-daemon -S --quiet --pidfile $PID_PATH --exec $DAEMON
}

# Function that stops the daemon/service
#
do_stop()
{
    echo -n "stop $DESC:\n"
    start-stop-daemon -K --quiet --pidfile $PID_PATH --name $NAME
}

case "$1" in
    start)
    do_start
    ;;

    stop)
    do_stop
    ;;

    restart)
    do_stop
    do_start
    ;;

    *)
    echo "Usage: $NAME {start|stop|restart}"
    ;;
esac
