#!/bin/sh

### BEGIN INIT INFO
# Provides:	     uwsgi
# Required-Start:    $local_fs
# Required-Stop:     $local_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: starts uwsgi
# Description:       starts uwsgi
### END INIT INFO

DESC=uwsgi
NAME=uwsgi
DAEMON=/usr/local/bin/uwsgi
PID_PATH=/var/run/uwsgi.pid
INI_PATH=/home/pi/max/app.ini
HOME_DIR=/home/pi


# Function that starts the daemon/service
#
do_start() {
    echo -n "start $DESC:\n"
    cd $HOME_DIR
    start-stop-daemon -S --quiet --pidfile $PID_PATH --exec $DAEMON -- --ini $INI_PATH
}

# Function that stops the daemon/service
#
do_stop() {
    echo -n "stop $DESC:\n"
    start-stop-daemon -K --quiet --pidfile $PID_PATH --name $NAME
}

case "$1" in
    start)
    do_start
    ;;

    stop)
    do_stop
    ;;

    restart)
    do_stop
    sleep 1
    do_start
    ;;

    *)
    echo "Usage: $NAME {start|stop|restart}"
    ;;
esac
